// Chapter 17/End of Chapter/webapp/src/header.tsx
import { createElement } from "./tools/jsxFactory";
import { Order } from "./data/entities";

export class Header {

    props: {
        order: Order,
        submitCallback: () => void
    }

    getContent(): HTMLElement {
        let count = this.props.order.productCount;
        return <div className="p-1 bg-secondary text-white text-end">
            { count === 0 ? "(No Selection)" 
                : `${ count } product(s), $` 
                        + `${ this.props.order.total.toFixed(2)}` }
            <button className="btn btn-sm btn-primary m-1" 
                    onclick={ this.props.submitCallback }>
                Submit Order
            </button>
        </div>
    }
}

// Chapter 18/angularapp/src/app/header.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";
import { Order } from './data/entities';

@Component({
    selector: "header",
    templateUrl: "./header.component.html"
})
export class Header {

    @Input()
    order = new Order();

    @Output()
    submit = new EventEmitter<void>();

    get headerText(): string {
        let count = this.order.productCount;
        return count === 0 ? "(No Selection)"
            : `${ count } product(s), $${ this.order.total.toFixed(2)}`
    }
}
